---

- hosts: elastic_servers
  become: true

  vars_prompt:
    - name: "seriously_delete_elasticsearch"
      prompt: Type "yes" to delete elasticsearch
      private: false
      default: "No"


  tasks:
    # - name: Verify user wants to delete elasticsearch
    #   pause: prompt='Please confirm you want to delete Elasticsearch! Press return to continue. Press Ctrl+c and then "a" to abort'

    - name: Include set-vars role
      include_role:
        name: set-vars

    - name: Ensure Elasticsearch is removed
      yum:
        lock_timeout: 180  # wait up to 3 minutes for a lock ansible/ansible#57189
        name: elasticsearch
        state: absent
      when: seriously_delete_elasticsearch == "yes"

    - name: Remove {{ m_meza_data }}/elasticsearch
      file:
        path: "{{ m_meza_data }}/elasticsearch"
        state: absent
      when: seriously_delete_elasticsearch == "yes"

    - name: Remove /etc/elasticsearch
      file:
        path: "/etc/elasticsearch"
        state: absent
      when: seriously_delete_elasticsearch == "yes"
